# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, "**workflow**" ]
  pull_request:
    branches: [ main, "**workflow**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install pakages
        run: npm ci
      
      - name: Run eslint
        run: ./node_modules/.bin/eslint --max-warnings 0 ./
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Setup nodejs
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install pacakges
        run: npm ci

      - name: Run nodejs build
        run: node ./src/build.js
        
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build bookmarklet
          
